module.exports = Campaigns = [
    {id:1,
      name:"AVC - Chef ki khoj",
      details:"Apollo AVC's 'Chef Ki Khoj' seeks talented chefs to showcase their culinary skills in an exciting competition. Apply now!",
      start_date:"2024-09-10 18:30:00",
      end_date:"2024-09-25 18:30:00",
      poster_url:"https://storage.googleapis.com/vguard_staging_bucket/apollo/appImages/Campaign/Poster/d5c50fd7-e352-4aa4-ab95-e101d9594be3.png",
      collaterals:[{"Campaign Participation Kit":["https://storage.googleapis.com/vguard_staging_bucket/apollo/appImages/Campaign/Poster/image9.png"]},
    {"Registration Form":["https://storage.googleapis.com/vguard_staging_bucket/apollo/appImages/Campaign/Poster/image11.png"]},
{"Letter":["https://storage.googleapis.com/vguard_staging_bucket/apollo/appImages/Campaign/Poster/image12.png"]},
{"Instruction Booklet":["https://storage.googleapis.com/vguard_staging_bucket/apollo/appImages/Campaign/Poster/image13.png"]},
{"Teasers/Reminders fro social media":["https://storage.googleapis.com/vguard_staging_bucket/apollo/appImages/Campaign/Poster/image10.png"]}]

    },
    {id:2,
      name:"AVC - Talent ki khoj",
      details:"Apollo AVC's 'Talent Ki Khoj' seeks talented chefs to showcase their culinary skills in an exciting competition. Apply now!",
      start_date:"2024-09-10 18:30:00",
      end_date:"2024-09-25 18:30:00",
      poster_url:"https://storage.googleapis.com/vguard_staging_bucket/apollo/appImages/Campaign/Poster/image%20(4).png",
      collaterals:[{"Campaign Participation Kit":["https://storage.googleapis.com/vguard_staging_bucket/apollo/appImages/Campaign/Poster/image9.png"]},
      {"Registration Form":["https://storage.googleapis.com/vguard_staging_bucket/apollo/appImages/Campaign/Poster/image11.png"]},
  {"Letter":["https://storage.googleapis.com/vguard_staging_bucket/apollo/appImages/Campaign/Poster/image12.png"]},
  {"Instruction Booklet":["https://storage.googleapis.com/vguard_staging_bucket/apollo/appImages/Campaign/Poster/image13.png"]},
  {"Teasers/Reminders fro social media":["https://storage.googleapis.com/vguard_staging_bucket/apollo/appImages/Campaign/Poster/image10.png"]}]
      
    },
    {id:3,
      name:"Wonder Woman contest",
      details:"Apollo AVC's 'Wonder Woman contest' seeks talented chefs to showcase their culinary skills in an exciting competition. Apply now!",
      start_date:"2024-09-10 18:30:00",
      end_date:"2024-09-25 18:30:00",
      poster_url:"https://storage.googleapis.com/vguard_staging_bucket/apollo/appImages/Campaign/Poster/image%20(5).png",
      collaterals:[{"Campaign Participation Kit":["https://storage.googleapis.com/vguard_staging_bucket/apollo/appImages/Campaign/Poster/image9.png"]},
      {"Registration Form":["https://storage.googleapis.com/vguard_staging_bucket/apollo/appImages/Campaign/Poster/image11.png"]},
  {"Letter":["https://storage.googleapis.com/vguard_staging_bucket/apollo/appImages/Campaign/Poster/image12.png"]},
  {"Instruction Booklet":["https://storage.googleapis.com/vguard_staging_bucket/apollo/appImages/Campaign/Poster/image13.png"]},
  {"Teasers/Reminders fro social media":["https://storage.googleapis.com/vguard_staging_bucket/apollo/appImages/Campaign/Poster/image10.png"]}]
      
    },
    {id:3,
      name:"Wow - Chef ki khoj 2",
      details:"Apollo AVC's 'Wow - Chef ki khoj 2' seeks talented chefs to showcase their culinary skills in an exciting competition. Apply now!",
      start_date:"2024-09-10 18:30:00",
      end_date:"2024-09-25 18:30:00",
      poster_url:"https://storage.googleapis.com/vguard_staging_bucket/apollo/appImages/Campaign/Poster/image3.png",
      collaterals:[{"Campaign Participation Kit":["https://storage.googleapis.com/vguard_staging_bucket/apollo/appImages/Campaign/Poster/image9.png"]},
      {"Registration Form":["https://storage.googleapis.com/vguard_staging_bucket/apollo/appImages/Campaign/Poster/image11.png"]},
  {"Letter":["https://storage.googleapis.com/vguard_staging_bucket/apollo/appImages/Campaign/Poster/image12.png"]},
  {"Instruction Booklet":["https://storage.googleapis.com/vguard_staging_bucket/apollo/appImages/Campaign/Poster/image13.png"]},
  {"Teasers/Reminders fro social media":["https://storage.googleapis.com/vguard_staging_bucket/apollo/appImages/Campaign/Poster/image10.png"]}]
      
    },
    {id:3,
      name:"Emerging Turks",
      details:"Apollo AVC's 'Talent Ki Khoj' seeks talented chefs to showcase their culinary skills in an exciting competition. Apply now!",
      start_date:"2024-09-10 18:30:00",
      end_date:"2024-09-25 18:30:00",
      poster_url:"https://storage.googleapis.com/vguard_staging_bucket/apollo/appImages/Campaign/Poster/image%20(6).png",
      collaterals:[{"Campaign Participation Kit":["https://storage.googleapis.com/vguard_staging_bucket/apollo/appImages/Campaign/Poster/image9.png"]},
      {"Registration Form":["https://storage.googleapis.com/vguard_staging_bucket/apollo/appImages/Campaign/Poster/image11.png"]},
  {"Letter":["https://storage.googleapis.com/vguard_staging_bucket/apollo/appImages/Campaign/Poster/image12.png"]},
  {"Instruction Booklet":["https://storage.googleapis.com/vguard_staging_bucket/apollo/appImages/Campaign/Poster/image13.png"]},
  {"Teasers/Reminders fro social media":["https://storage.googleapis.com/vguard_staging_bucket/apollo/appImages/Campaign/Poster/image10.png"]}]
      
    },
    {id:3,
      name:"JAB FIT TAB HIT",
      details:"Apollo AVC's 'JAB FIT TAB HIT' seeks talented chefs to showcase their culinary skills in an exciting competition. Apply now!",
      start_date:"2024-09-10 18:30:00",
      end_date:"2024-09-25 18:30:00",
      poster_url:"https://storage.googleapis.com/vguard_staging_bucket/apollo/appImages/Campaign/Poster/image%20(7).png",
      collaterals:[{"Campaign Participation Kit":["https://storage.googleapis.com/vguard_staging_bucket/apollo/appImages/Campaign/Poster/image9.png"]},
      {"Registration Form":["https://storage.googleapis.com/vguard_staging_bucket/apollo/appImages/Campaign/Poster/image11.png"]},
  {"Letter":["https://storage.googleapis.com/vguard_staging_bucket/apollo/appImages/Campaign/Poster/image12.png"]},
  {"Instruction Booklet":["https://storage.googleapis.com/vguard_staging_bucket/apollo/appImages/Campaign/Poster/image13.png"]},
  {"Teasers/Reminders fro social media":["https://storage.googleapis.com/vguard_staging_bucket/apollo/appImages/Campaign/Poster/image10.png"]}]
      
    }
  ]